# Site settings
debug: false
title: 'Datalogic Mobile Computing Developer Community'
tagline: 'Ready for Android?'

encoding: UTF-8
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->

url: 'https://datalogic.github.io'
baseurl: &baseurl ''
analytics_tracking_id: 'UA-77632025-1'
apireference_url: &apireference_url 'https://datalogic.github.io/android-sdk-docs'
addonxml_url: 'https://datalogic.github.io/android-sdk-addon/addon.xml'
samples_url:
  astudio: 'https://github.com/datalogic/android-samples-astudio'
  apk: 'https://github.com/datalogic/android-samples-astudio/releases/download/v2'
